# Generated by Django 4.0.1 on 2022-06-06 15:03

import accounts.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profile_pic.png', null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='accounts.customer')),
                ('reader_type', models.CharField(blank=True, choices=[('Male', 'Nam'), ('Female', 'Nữ')], max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('rId', models.CharField(default=accounts.models.pk_gen, max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
            bases=('accounts.customer',),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='accounts.customer')),
                ('certificate', models.CharField(blank=True, choices=[('Baccalaureate', 'Tú tài'), ('Intermediate', 'Trung cấp'), ('College1', 'Cao đẳng'), ('College2', 'Đại học'), ('Master', 'Thạc sĩ'), ('Doctor', 'Tiến sĩ')], max_length=200, null=True)),
                ('position', models.CharField(blank=True, choices=[('President', 'Giám đốc'), ('Vice President', 'Phó giám đốc'), ('Manager', 'Trưởng phòng'), ('Deputy', 'Phó phòng'), ('Staff', 'Nhân viên')], max_length=200, null=True)),
                ('service', models.CharField(blank=True, choices=[('Librarian', 'Thủ thư'), ('Cashier', 'Thủ quỹ'), ('Stockkeeper', 'Thủ kho'), ('Board of manager', 'Ban giám đốc')], max_length=200, null=True)),
                ('sId', models.CharField(default=accounts.models.staff_pk_gen, max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
            bases=('accounts.customer',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('cover_pic', models.ImageField(blank=True, default='logo.png', null=True, upload_to='')),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('pubYear', models.PositiveIntegerField(default=2022, validators=[django.core.validators.MaxValueValidator(2023), django.core.validators.MinValueValidator(1500)])),
                ('addDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('ctg', models.ManyToManyField(blank=True, to='accounts.BookCategory')),
            ],
        ),
    ]
