# Generated by Django 3.2.5 on 2022-06-14 08:48

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borroworder',
            name='list',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='borroworder',
            name='status',
            field=models.CharField(blank=True, choices=[('Chờ xác nhận', 'Chờ xác nhận'), ('Đang soạn sách', 'Đang soạn sách'), ('Hoàn thành', 'Hoàn thành'), ('Đã nhận sách', 'Đã nhận sách')], default='Chờ xác nhận', max_length=200, null=True),
        ),
    ]
