# Generated by Django 4.0.1 on 2022-06-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finereceipts',
            name='date_pay_fine',
        ),
        migrations.AddField(
            model_name='finereceipts',
            name='debt',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='finereceipts',
            name='debt_left',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
