# Generated by Django 4.0.1 on 2022-06-16 17:12

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='list_book',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='borroworder',
            name='list_book',
            field=jsonfield.fields.JSONField(),
        ),
    ]
