# Generated by Django 4.0.1 on 2022-06-16 10:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnbook',
            name='list_book',
        ),
        migrations.AddField(
            model_name='returnbook',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pubYear',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(2023), django.core.validators.MinValueValidator(2014)]),
        ),
        migrations.AlterField(
            model_name='bookliquidation',
            name='reason',
            field=models.CharField(choices=[('lost', 'Mất'), ('damaged', 'Hư hỏng'), ('user_lost', 'Người dùng làm mất')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='birth',
            field=models.DateField(null=True),
        ),
    ]
