# Generated by Django 3.2.5 on 2022-06-14 10:49

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnbook',
            name='book',
        ),
        migrations.AddField(
            model_name='returnbook',
            name='date_borrow',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='returnbook',
            name='list_book',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
