<<<<<<< HEAD
# Generated by Django 4.0.1 on 2022-06-16 18:20
=======
# Generated by Django 4.0.1 on 2022-06-16 17:12
>>>>>>> af634546cfced03728057929b17df90271ff259f

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='list_book',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='borroworder',
            name='list_book',
            field=jsonfield.fields.JSONField(),
        ),
    ]
