# Generated by Django 4.0.1 on 2022-06-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_finereceipts_date_pay_fine_finereceipts_debt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finereceipts',
            name='date_pay_fine',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
