# Generated by Django 4.0.1 on 2022-06-06 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_reader_customer_ptr_remove_staff_customer_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='customer',
        ),
    ]
