# Generated by Django 4.0.1 on 2022-06-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('ctg', models.CharField(max_length=200, null=True)),
                ('auth', models.CharField(max_length=200, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('publisher', models.CharField(max_length=200, null=True)),
                ('pubYear', models.DateTimeField(null=True)),
            ],
        ),
    ]
