# Generated by Django 4.0.1 on 2022-06-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_finereceipts_debt_finereceipts_debt_left_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FineReceipts',
            new_name='FineReceipt',
        ),
    ]
