# Generated by Django 3.2.5 on 2022-06-14 09:28

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220614_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borroworder',
            old_name='list',
            new_name='list_book',
        ),
        migrations.RemoveField(
            model_name='borrowbook',
            name='book',
        ),
        migrations.RemoveField(
            model_name='borroworder',
            name='book',
        ),
        migrations.AddField(
            model_name='borrowbook',
            name='list_book',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
