# Generated by Django 4.0.1 on 2022-06-09 15:30

import django.core.validators
from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_book_number_of_book_remain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='number_of_book_remain',
            field=models.PositiveIntegerField(default=1, null=True, validators=[django.core.validators.MaxValueValidator(django.db.models.fields.Field.value_from_object), django.core.validators.MinValueValidator(1)]),
        ),
    ]
