# Generated by Django 4.0.1 on 2022-06-14 12:23

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220614_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='list_book',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='borroworder',
            name='list_book',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='returnbook',
            name='list_book',
            field=jsonfield.fields.JSONField(),
        ),
    ]
