# Generated by Django 4.0.1 on 2022-06-16 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_finereceipt_remove_returnbook_list_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pubYear',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='penaltyticket',
            name='reader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.book'),
        ),
    ]
