# Generated by Django 4.0.1 on 2022-06-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_borrowbook_list_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penaltyticket',
            name='book',
        ),
    ]
