# Generated by Django 4.0.1 on 2022-06-15 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_returnbook_list_book_returnbook_book'),
        ('accounts', '0003_rename_finereceipts_finereceipt'),
    ]

    operations = [
    ]
