# Generated by Django 4.0.1 on 2022-06-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_book_pubyear_alter_penaltyticket_reader'),
    ]

    operations = [
        migrations.AddField(
            model_name='penaltyticket',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
