# Generated by Django 4.0.1 on 2022-06-15 04:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_finereceipts_date_pay_fine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pubYear',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(2023), django.core.validators.MinValueValidator(1500)]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='birth',
            field=models.DateField(null=True),
        ),
    ]
