# Generated by Django 4.0.1 on 2022-06-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_pic',
            field=models.ImageField(blank=True, default='logo.png', null=True, upload_to=''),
        ),
    ]
