# Generated by Django 4.0.1 on 2022-06-16 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_penaltyticket_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='penaltyticket',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.book'),
        ),
    ]
