# Generated by Django 4.0.1 on 2022-06-15 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_finereceipts_finereceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finereceipt',
            name='reader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.reader'),
        ),
        migrations.AlterField(
            model_name='finereceipt',
            name='staff',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staff'),
        ),
    ]
