# Generated by Django 3.2.5 on 2022-06-15 10:16

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_finereceipts_date_pay_fine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pubYear',
            field=models.PositiveIntegerField(null=True, validators=[accounts.models.MyMaxValueValidator(2023), accounts.models.MyMinValueValidator(2014)]),
        ),
        migrations.AlterField(
            model_name='bookliquidation',
            name='reason',
            field=models.CharField(choices=[('lost', 'Mất'), ('damaged', 'Hư hỏng'), ('user_lost', 'Người dùng làm mất')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='birth',
            field=models.DateField(null=True),
        ),
    ]
