# Generated by Django 3.2.5 on 2022-06-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_finereceipts_date_pay_fine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birth',
            field=models.DateField(null=True),
        ),
    ]
