# Generated by Django 4.0.1 on 2022-06-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_book_number_of_book_remain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='number_of_book_remain',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
