# Generated by Django 4.0.1 on 2022-06-16 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_penaltyticket_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='penaltyticket',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.book'),
        ),
        migrations.AlterField(
            model_name='penaltyticket',
            name='reader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.reader'),
        ),
    ]
