# Generated by Django 4.0.1 on 2022-06-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_returnbook_list_book_returnbook_book'),
        ('accounts', '0004_alter_finereceipt_reader_alter_finereceipt_staff'),
    ]

    operations = [
    ]
