# Generated by Django 3.2.5 on 2022-06-03 01:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_book_cover_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pubYear',
            new_name='inputDate',
        ),
        migrations.AlterField(
            model_name='book',
            name='amount',
            field=models.PositiveIntegerField(default=2022, validators=[django.core.validators.MaxValueValidator(2022), django.core.validators.MinValueValidator(1500)]),
        ),
    ]
