# Generated by Django 4.0.1 on 2022-06-15 05:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_book_pubyear_alter_customer_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pubYear',
            field=models.PositiveIntegerField(error_messages={'invalid_choice': 'Chỉ được nhận sách xuất bản trong vòng 8 năm'}, null=True, validators=[django.core.validators.MaxValueValidator(2023), django.core.validators.MinValueValidator(2014)]),
        ),
    ]
