# Generated by Django 4.0.1 on 2022-06-15 09:46

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_book_pubyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pubYear',
            field=models.PositiveIntegerField(null=True, validators=[accounts.models.MyMaxValueValidator(2023), accounts.models.MyMinValueValidator(2014)]),
        ),
        migrations.AlterField(
            model_name='bookliquidation',
            name='reason',
            field=models.CharField(choices=[('lost', 'Mất'), ('damaged', 'Hư hỏng'), ('user_lost', 'Người dùng làm mất')], max_length=200, null=True),
        ),
    ]
