# Generated by Django 4.0.1 on 2022-06-15 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20220616_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finereceipt',
            name='reader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.reader'),
        ),
        migrations.AlterField(
            model_name='finereceipt',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staff'),
        ),
    ]
