# Generated by Django 4.0.1 on 2022-06-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_book_description_alter_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='service',
            field=models.CharField(blank=True, choices=[('Librarian', 'Thủ thư'), ('Cashier', 'Thủ quỹ'), ('Stockkeeper', 'Thủ kho'), ('Manager deparment', 'Ban giám đốc')], max_length=200, null=True),
        ),
    ]
