# Generated by Django 4.0.1 on 2022-06-16 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20220616_0138'),
        ('accounts', '0006_alter_finereceipt_reader_alter_finereceipt_staff'),
    ]

    operations = [
    ]
