# Generated by Django 4.0.1 on 2022-06-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_book_description_alter_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='finereceipts',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
