# Generated by Django 3.2.5 on 2022-06-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220603_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ctg',
        ),
        migrations.AddField(
            model_name='book',
            name='ctg',
            field=models.ManyToManyField(to='accounts.Category_book'),
        ),
    ]
