# Generated by Django 4.0.1 on 2022-06-15 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customer_birth'),
        ('accounts', '0006_alter_book_pubyear_alter_bookliquidation_reason'),
    ]

    operations = [
    ]
