# Generated by Django 4.0.1 on 2022-06-11 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_staff_service'),
        ('accounts', '0007_finereceipts_reason'),
        ('accounts', '0007_reader_creator'),
    ]

    operations = [
    ]
