# Generated by Django 3.2.5 on 2022-06-12 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_cart_reader'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowOder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Inprocess', 'Đang soạn sách'), ('Complete', 'Hoàn thành')], max_length=200, null=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.cart')),
            ],
        ),
    ]
