# Generated by Django 3.2.5 on 2022-06-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220603_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='address',
        ),
        migrations.AddField(
            model_name='customer',
            name='birth',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='ctg',
            field=models.ManyToManyField(to='accounts.Category_reader'),
        ),
    ]
