# Generated by Django 3.2.5 on 2022-06-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220603_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birth',
            field=models.DateTimeField(null=True),
        ),
    ]
