# Generated by Django 4.0.1 on 2022-06-11 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_20220611_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finereceipts',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='creator',
        ),
        migrations.CreateModel(
            name='PenaltyTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('fine', models.PositiveIntegerField(default=0, null=True)),
                ('reader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.reader')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staff')),
            ],
        ),
    ]
