# Generated by Django 3.2.5 on 2022-06-12 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_borrowoder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowoder',
            name='cart',
        ),
        migrations.AddField(
            model_name='borrowoder',
            name='reader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.reader'),
        ),
    ]
