# Generated by Django 3.2.5 on 2022-06-12 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20220612_1501'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BorrowOder',
            new_name='BorrowOrder',
        ),
    ]
