# Generated by Django 3.2.5 on 2022-06-11 02:52

import accounts.initial_func
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_finereceipts_reason_remove_reader_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='rId',
            field=models.CharField(default=accounts.initial_func.pk_gen, editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='sId',
            field=models.CharField(default=accounts.initial_func.staff_pk_gen, editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
