# Generated by Django 4.0.1 on 2022-06-05 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customer_birth'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category_reader',
            new_name='CategoryReader',
        ),
    ]
