# Generated by Django 3.2.5 on 2022-06-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_borrowoder_borroworder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borroworder',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending ', 'Chờ xác nhận'), ('Inprocess', 'Đang soạn sách'), ('Complete', 'Hoàn thành')], default='Chờ xác nhận', max_length=200, null=True),
        ),
    ]
