# Generated by Django 3.2.5 on 2022-06-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_borroworder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='number_of_book_remain',
            field=models.PositiveIntegerField(default=models.PositiveIntegerField(default=1, null=True), null=True),
        ),
    ]
