# Generated by Django 4.0.1 on 2022-06-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customer_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='ctg',
        ),
        migrations.AddField(
            model_name='customer',
            name='reader_type',
            field=models.CharField(blank=True, choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='CategoryReader',
        ),
    ]
