# Generated by Django 4.0.1 on 2022-06-05 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_customer_ctg_customer_reader_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category_book',
            new_name='BookCategory',
        ),
    ]
