# Generated by Django 4.0.1 on 2022-06-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_auth_book_author_rename_amount_book_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='ctg',
            field=models.ManyToManyField(blank=True, to='accounts.BookCategory'),
        ),
    ]
