# Generated by Django 3.2.5 on 2022-06-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_book_number_of_book_remain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='number_of_book_remain',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
