# Generated by Django 4.0.1 on 2022-06-05 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_book_author_alter_book_ctg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.customer')),
                ('certificate', models.CharField(blank=True, choices=[('Baccalaureate', 'Tú tài'), ('Intermediate', 'Trung cấp'), ('College1', 'Cao đẳng'), ('College2', 'Đại học'), ('Master', 'Thạc sĩ'), ('Doctor', 'Tiến sĩ')], max_length=200, null=True)),
                ('position', models.CharField(blank=True, choices=[('President', 'Giám đốc'), ('Vice President', 'Phó giám đốc'), ('Manager', 'Trưởng phòng'), ('Deputy', 'Phó phòng'), ('Staff', 'Nhân viên')], max_length=200, null=True)),
                ('service', models.CharField(blank=True, choices=[('Librarian', ''), ('Cashier', ''), ('Stockkeeper', ''), ('Board of manager', 'Ban giám đốc')], max_length=200, null=True)),
            ],
            bases=('accounts.customer',),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='reader_type',
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.customer')),
                ('reader_type', models.CharField(blank=True, choices=[('Male', 'Nam'), ('Female', 'Nữ')], max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
            ],
            bases=('accounts.customer',),
        ),
    ]
