# Generated by Django 4.0.1 on 2022-06-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_book_number_of_book_remain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GetBook',
        ),
    ]
