# Generated by Django 4.0.1 on 2022-06-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_staff_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='service',
            field=models.CharField(blank=True, choices=[('Librarian', 'Thủ thư'), ('Cashier', 'Thủ quỹ'), ('Stockkeeper', 'Thủ kho'), ('Board of manager', 'Ban giám đốc')], max_length=200, null=True),
        ),
    ]
