# Generated by Django 4.0.1 on 2022-06-13 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_delete_getbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='nguoinhan',
        ),
    ]
