# Generated by Django 4.0.1 on 2022-06-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_staff_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
