# Generated by Django 4.0.1 on 2022-06-13 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_book_nguoinhan'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='nguoinhan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staff'),
        ),
    ]
