# Generated by Django 4.0.1 on 2022-06-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_reader_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='reader_type',
            field=models.CharField(blank=True, choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=200, null=True),
        ),
    ]
