# Generated by Django 4.0.1 on 2022-06-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_reader_reader_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='reader_type',
            field=models.CharField(blank=True, choices=[('Male', 'Nam'), ('Female', 'Nữ')], max_length=200, null=True),
        ),
    ]
