# Generated by Django 4.0.1 on 2022-06-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_book_nguoinhan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookliquidation',
            name='quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
