# Generated by Django 3.2.5 on 2022-06-05 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_customer_date_created'),
        ('accounts', '0020_alter_reader_reader_type'),
    ]

    operations = [
    ]
