# Generated by Django 4.0.1 on 2022-06-05 18:31

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_customer_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='rId',
            field=models.CharField(default=accounts.models.pk_gen, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='reader',
            name='customer_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='accounts.customer'),
        ),
    ]
